// Copies contract ABIs from the Foundry build into src/lib/abi.ts. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
const pick = (name) => JSON.parse(readFileSync(`contracts/out/${name}.sol/${name}.json`, "utf8")).abi;
const out = ["Contri", "MockAUSD", "ERC2771Forwarder"]
  .map((n) => `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(pick(n), null, 2)} as const;\n`)
  .join("\n");
writeFileSync("src/lib/abi.ts", `// Generated by scripts/abi.mjs from contracts/out. Do not edit.\n\n${out}`);
console.log("wrote src/lib/abi.ts");
